#!/usr/bin/env bash
# nginx on your web-01 server
# Nginx be listening on port 80
# When querying Nginx at its root with a GET request
# using curl, it must return a page that contains the string Holberton School

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
